# **Creating And Manipulating Arrays**

In [3]:
print("This is my first program in ")

This is my first program in 


**Importing NumPy**

In [4]:
import numpy as np

**Basic Array Creation**

In [5]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

**Converting List to Array**

In [6]:
a=[1,2,3.5,"hello"]
np.array(a)

array(['1', '2', '3.5', 'hello'], dtype='<U32')

In [7]:
b=[1,2,3.5]
np.array(b)

array([1. , 2. , 3.5])

**Matrix and Vectors**

In [ ]:
l=[[1,2,3],[4,5,6],[7,8,9]]
l
# vector are linear array 1D
# matric are multi dimensional array

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(l) # converting matrix into numPy array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Array Generation Function**

In [13]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [14]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((6,6)) # this will generate a matrix

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [16]:
np.linspace(1,5,8)

array([1.        , 1.57142857, 2.14285714, 2.71428571, 3.28571429,
       3.85714286, 4.42857143, 5.        ])

**Random Generation Function**

In [ ]:
np.random.rand(10) # generte random between 0 and 1

array([0.9619313 , 0.7023984 , 0.634324  , 0.70509269, 0.15641343,
       0.926367  , 0.19743229, 0.74270452, 0.48797613, 0.62743716])

In [ ]:
np.random.randn(10) #generatae random numbers between -1 to 1

array([-0.31878708,  0.77066357,  1.21478819,  1.3803087 ,  0.63712037,
        0.44070033,  0.40130743, -0.09272438,  1.22021348,  0.78613813])

In [ ]:
np.random.randint(6) #generate a random integer between 0 and 6

2

In [ ]:
np.random.randint(6,256) # generate a random integer between these two numbers

182

In [25]:
np.random.randint(6,254,21) # generate 21 random integeres between 6 and 254

array([148,  53,  15, 178,  12,  22,  90,  99,  96, 132, 101, 132, 124,
       197, 181, 204, 113,  94, 109, 162,   6], dtype=int32)

**Array Attributes**

In [26]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.size # number of elements

9

In [28]:
arr.shape # number of rows and number of coloumns

(3, 3)

In [29]:
arr.dtype

dtype('int64')

**Array Methods**

In [31]:
print(arr.min())

1


In [33]:
arr.max()

np.int64(9)

In [34]:
arr.sum()

np.int64(45)

In [ ]:
np.sum(arr,axis=0) # row wise sum

array([12, 15, 18])

In [ ]:
np.sum(arr,axis=1) # coloumn wise sum

array([ 6, 15, 24])

In [37]:
arr.mean()

np.float64(5.0)

In [38]:
arr.std()

np.float64(2.581988897471611)

In [ ]:
arr.argmax() # maximum elementn at which array index

np.int64(8)

In [40]:
arr.argmin()

np.int64(0)

**Reshaping and Resizing**

In [41]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [43]:
arr=arr.reshape(5,6) # convert a array into a matrix ( row, coloumn) BUT elment count in matrix and array must be same
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

# **Array Indexing**

In [44]:
print("Array Indexing and Slicing")

Array Indexing and Slicing


**Numpy Indexing and Slicing Of Vectors**

In [45]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [46]:
arr[9]

np.int64(20)

In [47]:
arrSliced=arr[1:9:2]
arrSliced

array([12, 14, 16, 18])

**Numpy Indexing and Slicing Of Matrix**

In [48]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [49]:
arr[4]

array([21, 22, 23, 24, 25])

In [50]:
arr[1,4]

np.int64(10)

In [ ]:
slice=arr[0:2,1:3] # [ row start:row end, col start: col end ]
slice

array([[2, 3],
       [7, 8]])

In [52]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

**Boolean Indexing**

In [53]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [54]:
boolIndex=arr%2==0
boolIndex

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [55]:
arr=arr[boolIndex]
arr

array([12, 14, 16, 18, 20])

# **Array Opeations**

In [56]:
print("Now i will be learning the array operations")

Now i will be learning the array operations


**Arithmatic Operations**

In [57]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])

In [58]:
a1

array([1, 2, 3, 4, 5])

In [59]:
a2

array([ 6,  7,  8,  9, 10])

In [61]:
# add two array
a1+a2

array([ 7,  9, 11, 13, 15])

In [62]:
# sub two array
a1-a2

array([-5, -5, -5, -5, -5])

In [63]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [64]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [65]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

In [66]:
a1//a2

array([0, 0, 0, 0, 0])

**Broadcasting**

In [108]:
l=[1,2,3,4,5]
arr=np.array(l)
arr

array([1, 2, 3, 4, 5])

In [67]:
arr+10 # adding 10 to all the elements of array

array([22, 24, 26, 28, 30])

**Deep and Shallow Copy**

In [76]:
arr=np.arange(1,6)
arr

array([1, 2, 3, 4, 5])

In [79]:
sliced=arr[:] # shallow copy
sliced=sliced*10
sliced

array([10, 20, 30, 40, 50])

In [80]:
arr

array([1, 2, 3, 4, 5])

In [81]:
arr1=arr # deep copy

In [82]:
arr1

array([1, 2, 3, 4, 5])

In [83]:
arr1[2]=345
arr1

array([  1,   2, 345,   4,   5])

In [84]:
arr # original array

array([  1,   2, 345,   4,   5])

**Matrix Operations**

In [85]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])

In [86]:
A

array([[1, 2],
       [3, 4]])

In [87]:
B

array([[5, 6],
       [7, 8]])

In [ ]:
A @ B # matrix multiplication

array([[19, 22],
       [43, 50]])

In [90]:
np.dot(A,B) # matrix multiplication

array([[19, 22],
       [43, 50]])

In [89]:
A.T # transpose

array([[1, 3],
       [2, 4]])

**Advanced Array Manipulation**

**Stacking Array**

In [91]:
A

array([[1, 2],
       [3, 4]])

In [92]:
B

array([[5, 6],
       [7, 8]])

In [93]:
a=np.array([[1,2,3,4]])
b=np.array([[5,6,7,8]])

In [94]:
a

array([[1, 2, 3, 4]])

In [95]:
b

array([[5, 6, 7, 8]])

In [ ]:
np.vstack((a,b)) # vertical stacking: all first row from a, the all second row from b element's

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
np.hstack((a,b)) # horizontal stacking

array([[1, 2, 3, 4, 5, 6, 7, 8]])

**Splitting Array**

In [98]:
c=np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.hsplit(c,2) # create 2 different matrix from this, ( vertically split array into 2 parts)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [ ]:
np.vsplit(c,4) # create 4 different matrix from this,( horizonatlly split array into 4 parts)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]